//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlToTable.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlToTable.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE dbo.usp_ReprocessDocuments
        ///	@Documents AS dbo.ids READONLY
        ///AS
        ///BEGIN
        ///
        ///	SET XACT_ABORT ON;
        ///
        ///	BEGIN TRANSACTION;
        ///
        ///		DELETE dbo.DocumentVariables
        ///		WHERE DocumentID IN (SELECT ID FROM @Documents)
        ///
        ///		DELETE dbo.Variables
        ///		WHERE VariableID IN
        ///		(
        ///			SELECT Variables.VariableID
        ///			FROM dbo.Variables
        ///				LEFT JOIN dbo.DocumentVariables
        ///					ON Variables.VariableID = DocumentVariables.VariableID
        ///			GROUP BY Variables.VariableID
        ///			HAVING COUNT(DocumentVariables.DocumentID) = 0
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmbeddedXmlUpgradeScript {
            get {
                return ResourceManager.GetString("EmbeddedXmlUpgradeScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[DocumentInfos]
        ///(
        ///	[DocumentID] [int] NOT NULL,
        ///	[SubjectID] [int] NOT NULL,
        ///	[GenerationDate] [datetime] NULL,
        ///	[Imported] [bit] NOT NULL,
        ///	[IsPriority] [bit] NOT NULL,
        ///	CONSTRAINT [PK_OriginInfo] PRIMARY KEY CLUSTERED 
        ///	(
        ///		[DocumentID] ASC
        ///	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///GO
        ///
        ///CREATE TABLE [dbo].[OriginalNames]
        ///(
        ///	[TableName] [sysname] NOT NULL,
        ///	[Column [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HierarchicalDatabaseCreationScript {
            get {
                return ResourceManager.GetString("HierarchicalDatabaseCreationScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE dbo.Variables ADD LongestValueLength INT NULL;
        ///GO
        ///
        ///DROP PROCEDURE [dbo].[usp_UpdateDataKinds];
        ///GO
        ///
        ///DROP TYPE [dbo].[Variable]
        ///GO
        ///
        ///CREATE TYPE [dbo].[Variable] AS TABLE(
        ///	[VariableName] [nvarchar](512) NOT NULL,
        ///	[DataKind] [varchar](50) NOT NULL,
        ///	[LongestValueLength] [int] NULL
        ///);
        ///GO
        ///
        ///CREATE PROCEDURE dbo.usp_UpdateVariables
        ///	@Updates AS dbo.[Variable] READONLY
        ///AS
        ///BEGIN
        ///
        ///	SET XACT_ABORT ON;
        ///
        ///	MERGE dbo.Variables AS dest
        ///	USING @Updates AS src
        ///	ON src.VariableName = dest [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LongestValueLengthUpgradeScript {
            get {
                return ResourceManager.GetString("LongestValueLengthUpgradeScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE dbo.Variables
        ///	SET DataKind = &apos;text&apos;
        ///	WHERE VariableID IN
        ///	(
        ///		SELECT Variables.VariableID
        ///		FROM dbo.Variables
        ///			JOIN dbo.DocumentVariables
        ///				ON Variables.VariableID = DocumentVariables.VariableID
        ///		WHERE DataKind = &apos;number&apos;
        ///			AND VariableValue LIKE &apos;%+&apos;
        ///	).
        /// </summary>
        internal static string NumberToTextCorrectionStatement {
            get {
                return ResourceManager.GetString("NumberToTextCorrectionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML to Table.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[DocumentInfos](
        ///	[DocumentID] [int] NOT NULL,
        ///	[ProviderID] [int] NOT NULL,
        ///	[SubjectID] [int] NOT NULL,
        ///	[GenerationDate] [datetime] NULL,
        ///	[Imported] [bit] NOT NULL,
        ///	[IsPriority] [bit] NOT NULL,
        /// CONSTRAINT [PK_DocumentInfos] PRIMARY KEY CLUSTERED 
        ///(
        ///	[DocumentID] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///GO
        ///
        ///CREATE TABLE [dbo].[DocumentVariables](
        ///	[DocumentID [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VerticalDatabaseCreationScript {
            get {
                return ResourceManager.GetString("VerticalDatabaseCreationScript", resourceCulture);
            }
        }
    }
}
